<?php

namespace Romero\PlanetaBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlanetasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanetasRepository extends EntityRepository
{
}
