indexA:
          path:     /
          defaults: { _controller: RomeroPlanetaBundle:Default:index }

verPlaneta:
          path:     /{planeta}
          defaults: { _controller: RomeroPlanetaBundle:Default:verPlaneta}

insert:
          path:     /insert/insertar
          defaults: { _controller: RomeroPlanetaBundle:Default:create }

update:
          path:    /update/{id}
          defaults: { _controller: RomeroPlanetaBundle:Default:update}

three:
          path:     /planetaria/sistema
          defaults: { _controller: RomeroPlanetaBundle:Default:sistema }

comparador:
          path:     /planetaria/comparador
          defaults: { _controller: RomeroPlanetaBundle:Default:comparador }

portfolio:
          path:     /prueba/portfolio
          defaults: { _controller: RomeroPlanetaBundle:Default:portfolio}